# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.143
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.app/desktop/v0.0.143/planton-desktop-v0.0.143-windows-x64-setup.exe
  InstallerSha256: 4B13C20D2A895E8588D4D7204531E23F20A3C9C35012151A9B787D1D91BDA13B
ManifestType: installer
ManifestVersion: 1.12.0
