# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.155
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.ai/client-apps/planton/desktop/v0.0.155/planton-desktop-v0.0.155-windows-x64-setup.exe
  InstallerSha256: 364130971CDBD36DAF5920DA21BFD8F636F9A4A1FE2349E185B5AA8BF8B91A09
ManifestType: installer
ManifestVersion: 1.12.0
