# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.151
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.ai/client-apps/planton/desktop/v0.0.151/planton-desktop-v0.0.151-windows-x64-setup.exe
  InstallerSha256: 829E4C58E57BF530954EC414925D9535E52EDA1D5E3D23AC8AA918BD74A7BE6C
ManifestType: installer
ManifestVersion: 1.12.0
