# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.154
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.ai/client-apps/planton/desktop/v0.0.154/planton-desktop-v0.0.154-windows-x64-setup.exe
  InstallerSha256: E9145B895D7A4D4145D8749172B4C100F96FFDA9C94FA9939CB203DBDC75F359
ManifestType: installer
ManifestVersion: 1.12.0
