# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.117
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.app/desktop/v0.0.117/planton-desktop-v0.0.117-windows-x64-setup.exe
  InstallerSha256: 0CEC405514F601F8BA837CE884306B4DA5775ABA22A6ADD7A92C48A36D59B85D
ManifestType: installer
ManifestVersion: 1.12.0
