# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.107
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.app/desktop/v0.0.107/planton-desktop-v0.0.107-windows-x64-setup.exe
  InstallerSha256: 44092416184BA8DCF0ABFEAE215DF240E6F358987FB87E1F5E2A7E1BD0D212F6
ManifestType: installer
ManifestVersion: 1.12.0
