# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.156
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.ai/client-apps/planton/desktop/v0.0.156/planton-desktop-v0.0.156-windows-x64-setup.exe
  InstallerSha256: 73F8C523FF4664A118F61B8FE9A7F3E1E59114C7ED66531048BABC10A765DA28
ManifestType: installer
ManifestVersion: 1.12.0
