# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.148
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.ai/client-apps/planton/desktop/v0.0.148/planton-desktop-v0.0.148-windows-x64-setup.exe
  InstallerSha256: 5ACC9D5B48FBEB6BEC126F6EAE2650B8CE1B151785E7635C6020245F278671AA
ManifestType: installer
ManifestVersion: 1.12.0
