# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Planton.Desktop
PackageVersion: 0.0.127
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Planton
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- DisplayName: Planton
  Publisher: planton
  ProductCode: Planton
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Planton'
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.planton.app/desktop/v0.0.127/planton-desktop-v0.0.127-windows-x64-setup.exe
  InstallerSha256: A0D77D2DF7AE09CF39CF31FD02B8DCA49009D7BBA2942985CC3A07774AF751DF
ManifestType: installer
ManifestVersion: 1.12.0
